stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw
    - src/data/data_split.py
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/training.py
    outs:
    - models/gbr_model.pkl
